function y(b){this.onready=this.onfail=this.onsuccess=this.suppressAlert=this.password=this.user=this.async=this.url=this.postData=this.method=null;this.headers={};this.params=null;this.sendAsBinary=true;var a=null,c=null,e=null,d=null,h=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert,f=this;if(typeof b=="object")for(var i in b){if(typeof this[i]!="undefined")this[i]=b[i]}else this.url=b;if(window.XMLHttpRequest)a=new XMLHttpRequest;else if(window.ActiveXObject)a=new ActiveXObject("Microsoft.XMLHTTP");
else{h("Ajax request error: Unsupported browser.");return}this.send=this.send=function(){function g(){if(a.readyState==4){c=a.status+" - "+a.statusText;f.onready!=null&&f.onready(f);if(a.status==200){e=true;f.onsuccess!=null&&f.onsuccess(f)}else{e=false;f.suppressAlert!=true&&h(c);f.onfail!=null&&f.onfail(f)}d=false}}var k=null,l=null,j=null;if(f.method==null)k="GET";else if(typeof f.method!="string"&&(f.method.toUpperCase()!="GET"||f.method.toUpperCase()!="POST"||f.method.toUpperCase()!="PUT")){h('Invalid value for property: "method".');
return}else k=f.method.toUpperCase();if(k=="POST")if(f.postData!=null)if(typeof f.postData!="string"){h('Invalid value for property: "postData".');return}else j=f.postData;else j="";if(f.async==null)l=true;else if(f.async!=true&&f.async!=false){h('Invalid value for property: "async".');return}else l=f.async;if(typeof f.url!="string")h('Invalid value for property: "url".');else{if(f.user!=null)if(typeof f.user!="string"){h('Invalid value for property: "user".');return}if(f.password!=null)if(typeof f.password!=
"string"){h('Invalid value for property: "password".');return}if(f.onsuccess!=null)if(typeof f.onsuccess!="function"){h('Invalid value for event: "onsuccess".');return}if(f.onfail!=null)if(typeof f.onfail!="function"){h('Invalid value for event: "onfail".');return}if(f.onready!=null)if(typeof f.onready!="function"){h('Invalid value for event: "onready".');return}var r=f.url,t=f.params;if(typeof t=="object"){var n="";for(var o in t){var m=t[o],s=[];if(typeof m=="object"){if(m.length!=null&&m.length>
0)s=m}else s.push(m);for(m=0;m<s.length;m++){if(n!="")n+="&";n+=encodeURIComponent(o)+"="+encodeURIComponent(s[m])}}if(n!="")if(k.toUpperCase()=="POST"){if(j!=null&&j!="")j+="&";else j="";j+=n}else{t=r.split("?");if(t.length==2&&t[1]!="")r=t[0]+"?"+t[1]+"&"+n;else r+="?"+n}}try{typeof f.user=="string"&&typeof f.password=="string"?a.open(k,r,l,f.user,f.password):a.open(k,r,l);r=false;var p=f.headers;for(o in p){a.setRequestHeader(o,p[o]);if(o.toUpperCase()=="CONTENT-TYPE")r=true}if(k=="POST")r||a.setRequestHeader("Content-type",
"application/x-www-form-urlencoded")}catch(u){h(u);return}d=true;if(l==true)a.onreadystatechange=g;if(f.sendAsBinary==true)try{a.sendAsBinary(j)}catch(v){a.send(j)}else a.send(j);l!=true&&g()}};this.ok=this.I=function(){return e!=null?e:false};this.getResponseText=this.d=function(){return a.responseText};this.getResponseXML=this.t=function(){return a.responseXML};this.getStatus=this.c=function(){return a.status};this.getStatusText=this.k=function(){return a.statusText};this.getStatusMessage=this.u=
function(){return c};this.getAllResponseHeaders=this.getAllResponseHeaders=function(){if(e)try{return a.getAllResponseHeaders()}catch(g){h(g)}};this.getResponseHeader=this.getResponseHeader=function(g){if(e)try{return a.getResponseHeader(g)}catch(k){h(k)}};this.setRequestHeader=this.setRequestHeader=function(g,k){f.headers[g]=k};this.abort=this.abort=function(){if(!(d==null||d==true))try{a.abort()}catch(g){h(g)}}}
function z(b,a){var c,e,d,h="";if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;if(typeof c.handler=="function"){e=true;d=c.handler}else e=false}else if(a!=null&&typeof a=="function"){e=true;d=a}else e=false;c=new y(arguments[0]);c.async=e;c.onsuccess=function(f){h+=f.d();e==true&&d(h)};c.send();if(e==false)return h}
function C(b,a){var c,e,d,h=null,f=false;if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;if(c.saveResponse==true)f=true;if(typeof c.handler=="function"){e=true;d=c.handler}else e=false}else if(a!=null&&typeof a=="function"){e=true;d=a}else e=false;c=new y(arguments[0]);c.async=e;c.onsuccess=function(i){i=i.d();if(f&&typeof pui=="object")pui.savedJSON=i;try{h=eval("("+i+")")}catch(g){d(null,g);return}e==true&&d(h)};c.send();if(e==false)return h}
if(typeof window.pui=="undefined")window.pui={};window.RPGspRequest=y;window.pui.Ajax=y;window.pui.AjaxRequest=y;window.ajax=z;
window.ajaxXML=function(b,a){var c,e,d,h=null;if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;c.onfail=null;c.onsuccess=null;if(typeof c.handler=="function"){e=true;d=c.handler}else e=false}else if(a!=null&&typeof a=="function"){e=true;d=a}else e=false;c=new y(arguments[0]);c.async=e;c.onsuccess=function(f){h=f.t();e==true&&d(h)};c.send();if(e==false)return h};window.ajaxJSON=C;
window.ajaxSubmit=function(b,a){var c,e="",d=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert;if(typeof b=="object")c=b;else{c=document.getElementById(b);if(c==null)c=document.forms[b]}var h;if(c!=null)h=c.tagName;if(c==null||h==null||h.toUpperCase()!="FORM"){d("Ajax request error: Invalid form object.");return""}if(b.action==""){d("Ajax request error: Invalid form action.");return""}for(d=0;d<c.elements.length;d++){h=c.elements[d];if(h.name!=null&&h.name!=""){var f=false;if(h.tagName==
"INPUT"){var i=h.type;i=i.toLowerCase();if(i=="hidden")f=true;if(i=="password")f=true;if(i=="text")f=true;if(pui.ia(i))f=true;if(i=="")f=true;if(i=="checkbox"||i=="radio")if(h.checked)f=true}if(h.tagName=="TEXTAREA")f=true;if(h.tagName=="SELECT")f=true;if(f){if(e!="")e+="&";e+=h.name+"="+encodeURIComponent(h.value)}}}c=new y(c.action);c.method="POST";c.postData=e;var g="",k;if(a!=null&&typeof a=="function")k=true;else{k=false;c.async=false}c.onsuccess=function(l){g+=l.d();k==true&&a(g)};c.send();
if(k==false)return g};function D(b){var a;b=b!=null&&typeof b=="object"?b:document.getElementById(b);if(b==null)return"";a="";if(b.tagName.toLowerCase()=="div"){a=b.firstChild;a=a!=null&&a.tagName!=null&&a.tagName=="A"?a.innerHTML:b.innerHTML}if(b.tagName=="INPUT"&&b.type=="checkbox"){if(b.checked&&b.h!=null)return b.h;if(!b.checked&&b.Q!=null)return b.Q;return b.checked}if(b.tagName=="INPUT"||b.tagName=="TEXTAREA")a=b.value;if(b.tagName=="SELECT"){a=b.selectedIndex;a=a>=0?b.options[a].value:b.pui&&b.pui.properties&&b.pui.properties.value?
b.pui.properties.value:b.value}if(b.comboBoxWidget!=null)a=b.comboBoxWidget.getValue();if(b.v!=null)a=String(b.value);if(b.e!=null){a="";if(b.e.F&&b.e.J!=null)a=b.e.J;else if(!b.e.F&&b.e.H!=null)a=b.e.H}for(a=a.replace(/&nbsp;/g," ");a.indexOf(String.fromCharCode(160))!=-1;)a=a.replace(String.fromCharCode(160)," ");if(a==b.ba)a="";return a}function H(b){for(;b.charAt(0)==" ";)b=b.replace(b.charAt(0),"");return b}function I(b){return b.replace(/^\s*|\s*$/g,"")}
pui.detachCalendar=function(b){if(typeof b=="string")b=document.getElementById(b);b!=null&&pui.ma(b)};function J(b,a,c){var e=false,d=location.href;d=d.split("?")[0];d=d.split("/");if(d.length>2&&d[d.length-2].toLowerCase()=="auth")e=true;d="/profoundui/";if(e==true||c==true)d+="auth/";d+=b;if(a!=null&&a==true)d+="/"+PSID;if(pui.serverURL!=null)d=pui.serverURL+d;return d}pui.getProgramURL=J;pui.da=function(b){return pui.s(b).x};pui.ea=function(b){return pui.s(b).y};
pui.s=function(b){b=b||window.event;var a={x:0,y:0};if(b!=null&&b.touches!=null&&b.touches.length==1){a.x=b.touches[0].pageX;a.y=b.touches[0].pageY}else if(b!=null){if(b.pageX)a.x=b.pageX;else if(b.clientX)a.x=b.clientX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft);if(b.pageY)a.y=b.pageY;else if(b.clientY)a.y=b.clientY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)}return a};
function N(){var b={},a="";a=location.search.substring(1,location.search.length);if(a.length==0)return b;a=a.replace(/\+/g," ");a=a.split("&");for(var c=0;c<a.length;c++){var e=a[c].split("="),d=decodeURIComponent(e[0]),h="";if(e.length==2)h=decodeURIComponent(e[1]);b[d]=h}return b}if(typeof applyDesignProperty!="undefined")window.T=applyDesignProperty;
pui.o={r:function(b){for(var a="",c=0;c<b.length;c++){var e=b.charCodeAt(c);if(e<128)a+=String.fromCharCode(e);else{if(e>127&&e<2048)a+=String.fromCharCode(e>>6|192);else{a+=String.fromCharCode(e>>12|224);a+=String.fromCharCode(e>>6&63|128)}a+=String.fromCharCode(e&63|128)}}return a},q:function(b){for(var a="",c=0,e=c1=c2=0;c<b.length;){e=b.charCodeAt(c);if(e<128){a+=String.fromCharCode(e);c++}else if(e>191&&e<224){c2=b.charCodeAt(c+1);a+=String.fromCharCode((e&31)<<6|c2&63);c+=2}else{c2=b.charCodeAt(c+
1);c3=b.charCodeAt(c+2);a+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63);c+=3}}return a}};
pui.S={b:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",r:function(b){var a="",c,e,d,h,f,i,g=0;for(b=pui.o.r(b);g<b.length;){c=b.charCodeAt(g++);e=b.charCodeAt(g++);d=b.charCodeAt(g++);h=c>>2;c=(c&3)<<4|e>>4;f=(e&15)<<2|d>>6;i=d&63;if(isNaN(e))f=i=64;else if(isNaN(d))i=64;a=a+this.b.charAt(h)+this.b.charAt(c)+this.b.charAt(f)+this.b.charAt(i)}return a},q:function(b){var a="",c,e,d,h,f,i=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");i<b.length;){c=this.b.indexOf(b.charAt(i++));e=
this.b.indexOf(b.charAt(i++));h=this.b.indexOf(b.charAt(i++));f=this.b.indexOf(b.charAt(i++));c=c<<2|e>>4;e=(e&15)<<4|h>>2;d=(h&3)<<6|f;a+=String.fromCharCode(c);if(h!=64)a+=String.fromCharCode(e);if(f!=64)a+=String.fromCharCode(d)}return a=pui.o.q(a)}};
pui.downloadJSON=function(){if(pui.savedJSON==null)pui.alert("JSON is not available.");else{var b=pui.savedJSON;if(typeof JSON==="object"&&typeof JSON.parse==="function"&&typeof JSON.stringify==="function")try{b=JSON.stringify(JSON.parse(pui.savedJSON),null,"  ")}catch(a){}pui.aa("text/plain","json.txt",b)}};
pui.keepAlive=function(){var b;if(!(context=="genie"&&pui.f.g==true)){if(context=="dspf")b=pui.f==null?J("PUI0001200.pgm"):J("PUI0002110.pgm");else if(context=="genie")b=DOCUMENT_URI;else return false;if(pui.psid!=null&&pui.psid!="")b+="/"+pui.psid;if(pui.overrideSubmitUrl!=null&&typeof pui.overrideSubmitUrl=="function")try{b=pui.overrideSubmitUrl(b)}catch(a){}if(context=="genie")pui.w(pui.f.g=true);if(context=="dspf")pui.n=false;pui.oa();z({url:b,method:"post",params:{keepalive:"1"},sendAsBinary:false,
suppressAlert:true,handler:function(){pui.C();if(context=="genie")pui.w(pui.f.g=false);if(context=="dspf")pui.n=true;for(var c=0;c<pui.l.length;c++)pui.l[c].P()},onfail:function(c){pui.onoffline==null&&!pui["suppress comm errors"]&&pui.alert(pui.fa(c));pui.C();if(context=="genie")pui.w(pui.f.g=false);if(context=="dspf")pui.n=true;for(c=0;c<pui.l.length;c++)pui.l[c].P();pui.onoffline!=null&&pui.onoffline()}});return true}};
pui.getWindowSize=function(){var b,a;if(document.body&&document.body.offsetWidth){b=document.body.offsetWidth;a=document.body.offsetHeight}if(document.compatMode=="CSS1Compat"&&document.documentElement&&document.documentElement.offsetWidth){b=document.documentElement.offsetWidth;a=document.documentElement.offsetHeight}if(window.innerWidth&&window.innerHeight){b=window.innerWidth;a=window.innerHeight}if(b==null&&screen!=null)b=screen.width;if(a==null&&screen!=null)a=screen.height;if(b==null)b=800;
if(a==null)a=600;return{width:b,height:a}};pui.openURL=function(b){window.open(b)};pui.normalizeURL=function(b,a){if(b==null||typeof b!="string")return"";if(a==true&&window.puiMobileClient==null)return b;if(b.substr(0,5).toLowerCase()=="http:"||b.substr(0,6).toLowerCase()=="https:")return b;return pui.serverURL!=null?pui.serverURL+b:window.cordova&&b.substr(0,1)=="/"?b.substr(1):b};
pui.animate=function(b){var a=b.element;if(typeof a=="string")a=document.getElementById(a);if(a!=null){var c,e=b.effect;if(e=="fly in left"||e=="fly in right"||e=="fly out left"||e=="fly out right")c="left";else if(e=="fly in up"||e=="fly in down"||e=="fly out up"||e=="fly out down")c="top";else if(e=="fade in"||e=="fade out")c="opacity";else{c=b.properties;if(c==null){c=b.property;if(c==null)return}}if(typeof c=="string")c=[c];var d=b.duration;if(d==null)d="500ms";if(d.substr(d.length-1,1)!="s")d+=
"s";var h=parseInt(d)*1E3;if(d.length>2&&d.substr(d.length-2,2)=="ms")h=parseInt(d);var f=b.type;if(f==null)f="ease";var i=b.from,g=b.to;switch(e){case "fly in right":i=-a.offsetWidth;i+="px";g="0px";break;case "fly in left":i=a.offsetWidth;i+="px";g="0px";break;case "fly out left":g=-a.offsetWidth;g+="px";i="0px";break;case "fly out right":g=a.offsetWidth;g+="px";i="0px";break;case "fly out down":g=a.offsetHeight;g+="px";i="0px";break;case "fly out up":g=-a.offsetHeight;g+="px";i="0px";break;case "fly in up":i=
a.offsetHeight;i+="px";g="0px";break;case "fly in down":i=-a.offsetHeight;i+="px";g="0px";break;case "fade in":i="0";g="100";break;case "fade out":i="100";g="0";break}if(g!=null){var k="";for(e=0;e<c.length;e++){var l=c[e];if(k!="")k+=", ";k+=l+" "+d+" "+f}var j=["transition","MozTransition","WebkitTransition","msTransition","OTransition"];if(i!=null){if(typeof i=="string"||typeof i=="number")i=[i];for(e=0;e<c.length;e++){l=c[e];a.style[l]=i[e]}}setTimeout(function(){for(var r=0;r<j.length;r++)a.style[j[r]]=
k;setTimeout(function(){if(typeof g=="string"||typeof g=="number")g=[g];for(var t=0;t<c.length;t++)a.style[c[t]]=g[t];setTimeout(function(){for(var n=0;n<j.length;n++)a.style[j[n]]="";b.oncomplete!=null&&b.oncomplete()},h)},1)},1)}}};pui.getActiveElement=function(){return context=="genie"?lastActiveElement:pui.activeElement};pui.fieldExit=function(b){var a=pui.getActiveElement();if(a!=null){var c=false;if(b!=null)c=true;context=="genie"?fieldExit(a,c):pui.Y(a)}};
pui.showCalendar=function(b){var a=b;if(typeof b=="string")a=document.getElementById(b);if(a!=null)if(typeof a=="object"){var c=a.calimg;if(c!=null)if(c.click!=null&&typeof c.click=="function")c.click();else c.onclick!=null&&typeof c.onclick=="function"&&setTimeout(function(){c.onclick()},250)}};pui.getComputedStyle=function(b){var a=null;if(window.getComputedStyle)a=window.getComputedStyle(b);else if(b.currentStyle)a=b.currentStyle;return a};
pui.upload=function(b,a){var c=b.dir,e=b.overwrite===true,d;if(typeof b.slimit=="number")d=b.slimit;var h;if(typeof b.flimit=="number")h=b.flimit;var f="";if(typeof b.altname=="string")f=b.altname;var i;if(typeof b.allowedTypes&&b.allowedTypes instanceof Array)i=b.allowedTypes;if(h==null)h=b.files.length;if(d==null||i==null){for(var g,k=[],l=0;l<b.files.length;l++){var j=b.files[l],r=typeof j.type!="undefined"&&j.type!=""?j.type:"application/octet-stream";pui.U(k,r)==-1&&k.push(r);j=j.data&&j.data instanceof
ArrayBuffer?j.data.byteLength:j.size;j=Math.ceil(j/1048576);if(g==null||j>g)g=j}if(d==null)d=g;if(i==null)i=k}g=J("PUI0009109.PGM");g+="?AUTH="+encodeURIComponent(pui.appJob.auth);g+="&mode=ajax";g+="&r="+Math.floor(Math.random()*1E9);k=new FormData;k.append("dir",c);k.append("overwrite",e?"1":"0");k.append("flimit",h);k.append("slimit",d);k.append("altname",f);for(l=0;l<i.length;l++)k.append("type",i[l]);for(l=0;l<b.files.length;l++){j=b.files[l];if(j.data&&j.data instanceof ArrayBuffer){var t;try{t=
new Blob([j.data])}catch(n){c=new window.WebKitBlobBuilder;c.append(j.data);t=c.getBlob()}k.append("file",t)}else k.append("file",j);k.append("filename",j.name)}var o=new XMLHttpRequest;o.open("POST",g,true);o.onreadystatechange=function(){if(o.readyState==4){var m=true,s;if(o.status==200){var p;try{p=eval("("+o.responseText+")")}catch(u){m=false;s="Server response missing or invalid."}if(p){m=p.success;if(!m)if(p.key){s=pui.getLanguageText("runtimeMsg","upload "+p.key);if(p.key=="file limit")s=s.replace("&1",
h);if(p.key=="size limit")s=s.replace("&1",d)}else s=p.error}}else{m=false;s=o.status+" - "+o.statusText+"."}typeof a=="function"&&a(m,s)}};o.send(k)};pui.getCookie=function(b){var a=document.cookie.split(";"),c="",e="",d="",h="";for(h=0;h<a.length;h++){c=a[h].split("=");e=c[0].replace(/^\s+|\s+$/g,"");if(e==b){if(c.length>1)d=unescape(c[1].replace(/^\s+|\s+$/g,""));return d}}return null};
pui.setCookie=function(b,a,c,e,d,h){var f=new Date;f.setTime(f.getTime());if(c)c=c*1E3*60*60*24;f=new Date(f.getTime()+c);document.cookie=b+"="+escape(a)+(c?";expires="+f.toGMTString():"")+(e?";path="+e:"")+(d?";domain="+d:"")+(h?";secure":"")};pui.deleteCookie=function(b,a,c){if(pui.getCookie(b))document.cookie=b+"="+(a?";path="+a:"")+(c?";domain="+c:"")+";expires=Thu, 01-Jan-1970 00:00:01 GMT"};
pui.refresh=function(b){if(b==null)b={};var a=b.url;b=b.skin;pui.setCookie("puiRefreshId",pui.psid,null,"/");pui.skipConfirm=true;pui.shutdownOnClose=false;pui.confirmOnClose=false;if(b!=null){b="skin="+encodeURIComponent(b);a=window.location.href;var c=a.split("?");a=c[0];c=c[1];if(c==null)c="";qparms=c.split("&");c=false;for(var e=0;e<qparms.length;e++)if(qparms[e].length>=5&&qparms[e].substr(0,5).toLowerCase()=="skin="){qparms[e]=b;c=true}if(!c)if(qparms.length==1&&qparms[0]=="")qparms[0]=b;else qparms.push(b);
c=qparms.join("&");a=a+"?"+c}if(a!=null)window.location.href=a;else window.location.reload()};
pui.downloadURL=function(b){if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")return pui.is_ie?"":"data:text/html,<!DOCTYPE html><html><body><p>To download, please connect to a Profound UI session.</p></body></html>";var a=b.inline===true;if(b.id==null)return"";var c=J("PUI0009110.PGM");c+="?id="+encodeURIComponent(b.id);if(b.contentType!=null)c+="&type="+encodeURIComponent(b.contentType);if(a)c+="&inline=1";c+="&usehttprc=0";c+="&AUTH="+encodeURIComponent(pui.appJob.auth);
c+="&r="+Math.floor(Math.random()*1E9);return c};pui.download=function(b){var a=pui.downloadURL(b);b=b.inline===true;if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")b=true;b?pui.openURL(a):pui.link(a)};
pui.focusOnContainer=function(){setTimeout(function(){if(pui.a==null){pui.a=document.createElement("input");pui.a.type=pui.is_touch?"button":"text";pui.a.readOnly=true;pui.a.style.position="absolute";pui.a.style.left="-999px";pui.a.style.top="-999px";pui.a.style.width="10px";pui.a.style.borderStyle="none";pui.a.style.backgroundColor="transparent";pui.runtimeContainer.appendChild(pui.a)}pui.D=true;pui.a.focus();setTimeout(function(){pui.D=false},0)},1)};
pui.addCSS=function(b){var a=document.getElementsByTagName("head")[0],c=document.createElement("style");c.type="text/css";if(pui.is_old_ie)c.styleSheet.cssText=b;else c.innerHTML=b;a.appendChild(c)};pui.loadCSS=function(b){if(pui.B(b)!=null)return false;var a=document.getElementsByTagName("head")[0],c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("media","screen");c.setAttribute("href",pui.normalizeURL(b));a.appendChild(c);return true};
pui.removeCSS=function(b){var a=document.getElementsByTagName("head")[0],c=pui.B(b);if(c==null){c=a.getElementsByTagName("style");for(var e=0;e<c.length;e++){var d=c[e];if(d.innerHTML==b||d.styleSheet!=null&&d.styleSheet.cssText==b){a.removeChild(d);return true}}return false}else{a.removeChild(c);return true}};
pui.loadJS=function(b){if(b==null)return null;var a,c,e,d;if(typeof b=="string")a=b;if(typeof b=="object"){a=b.path;c=b.callback;e=b.onerror;d=b.test;if(d!=null&&typeof d=="function"&&d()==true)return false}if(a==null)return null;if(pui.ga(pui.normalizeURL(a))!=null)return false;b=document.getElementsByTagName("head")[0];var h=false,f=document.createElement("script");f.type="text/javascript";f.onreadystatechange=function(){if(f.readyState=="complete"||f.readyState=="loaded")if(!(d!=null&&typeof d==
"function"&&d()!=true)){!h&&c!=null&&c();h=true}};f.onload=function(){if(!(d!=null&&typeof d=="function"&&d()!=true)){!h&&c!=null&&c();h=true}};if(e)f.onerror=e;f.src=pui.normalizeURL(a);b.appendChild(f);return true};
pui.endOfSession=function(b){pui.confirmOnClose=false;pui.shutdownOnClose=false;if(window.puiMobileClient!=null&&window.puiMobileClient.showConnections!=null){window.puiMobileClient.showConnections();b!=null&&pui.alert(b)}else{var a=N().gobackto;if(a!=null){document.body.innerHTML="";b!=null&&pui.alert(b);location.href=a}if(navigator.app!=null&&navigator.app.exitApp!=null){document.body.innerHTML="";b!=null?pui.alert(b,function(){navigator.app.exitApp()}):navigator.app.exitApp()}}};
pui.alert=function(b,a,c,e){if(window.navigator!=null&&window.navigator.notification!=null&&window.navigator.notification.alert!=null)if(a==null&&c==null&&e==null&&window.puiMobileClient!=null&&window.puiMobileClient.alert!=null)window.puiMobileClient.alert(b);else{if(a==null)a=function(){};if(c==null)c="Profound UI";if(e==null)e="OK";window.navigator.notification.alert(b,a,c,e)}else alert(b)};pui.get=function(b){return I(D(b))};
pui.set=function(b,a){var c;c=typeof b=="object"?b:document.getElementById(b);if(c!=null){if(c.tagName=="DIV")if(c.v!=null)c.v.setValue(a);else if(c.comboBoxWidget!=null)c.comboBoxWidget.setValue(a);else if(c.button&&c.button.O)c.button.O.innerHTML=a;else c.innerHTML=a;if(c.tagName=="INPUT"||c.tagName=="SELECT"||c.tagName=="TEXTAREA")if(c.tagName=="INPUT"&&c.type=="checkbox")c.checked=typeof a=="boolean"?a:c.h!=null&&a==c.h?true:false;else c.value=a;if(context=="dspf"||pui.R&&c.j==null){c.modified=
true;var e=c.ra;if(c.id!=null&&c.id.indexOf(".")==-1&&c.A!=null)pui.X[c.A]=true;if(e!=null){e.ha();e.Z=true;pui.na(c,e.ca())}}if(context=="genie"&&c.j!=null&&c.j.idx!=null)pui.response[c.j.idx]=c;pui.V(c);if(c.pui&&c.pui.properties)c.pui.properties.value=a}};pui.getActiveContainer=function(){if(context=="genie"){for(var b=1,a=document.getElementById("window"+b);a;){var c=document.getElementById("window"+ ++b);if(c)a=c;else break}if(a)return a}else if(context=="dspf"&&pui.G)return pui.G;return pui.runtimeContainer};
pui.getDisplayType=function(){return pui.R?"5250-handler":context=="dspf"?"rdf":"5250"};
function O(b){function a(){if(!(h>=d.length)){var f=d[h].command,i=d[h].wait;h+=1;if(c==1||c==2){var g=i?"1":"0";g="http://localhost:"+(typeof pui["pc listener port"]=="number"?pui["pc listener port"]:80)+"/?cmd="+encodeURIComponent(f)+"&wait="+g;if(c==2){g+="&type=image&rnd="+String(Math.random())+String((new Date).getTime());i=new Image;i.onload=function(){a()};i.src=g}else{g=new pui.Ajax(g);g.method="GET";g.async=i?false:true;g.pa=true;g.ja=function(l){if(l.c()!=200){console.log("PC Command Listener comm. failure: "+
l.u());console.log("Command: "+f)}};g.ka=function(){a()};g.send()}}else if(c==3)C({url:J("PUI0009117.pgm"),method:"post",params:{cmd:f,auth:pui.appJob.auth},async:true,handler:function(l){if(l!=null)if(l.cmd){l="puilaunch:"+encodeURIComponent(l.cmd);var j=document.createElement("iframe");j.style.display="none";j.src=l;document.body.appendChild(j);setTimeout(function(){j!=null&&j.parentNode!=null&&document.body.removeChild(j);j=null;a()},5E3)}else l.error&&console.log("PC Command signing error:",l.error);
else console.log("Empty response from PC command signing program.")}});else{if(h==0&&d.length>0){i=[];for(g=0;g<d.length;g++)i.push("("+d[g].W+")");f=i.join(" && ")}try{e.runCommand(f)}catch(k){i='Unable to execute "'+f+'".\n\n';if(k!=null)i+=k.name+":\n\n"+k.message+".";alert(i)}}}}var c=0;if(pui["use pc listener"])c=1;if(window.HTTPS!=null&&window.HTTPS=="ON"&&c==1)c=2;if(pui["pc listener mode"])c=parseInt(pui["pc listener mode"]);if(typeof pui["pc command mode"]=="string")switch(pui["pc command mode"]){case "applet":c=
0;break;case "listener":c=1;break;case "listener_m2":c=2;break;case "launcher":c=3;break;default:c=0;console.log("Unsupported pc command mode:",pui["pc command mode"])}if(c==0){var e=document.getElementById("PCCommandApplet");if(!e){pui.p=b;loadPCCommandApplet("runCommandCb");return}}var d=[],h=0;d=typeof b=="string"?[{command:b,wait:false}]:b;a()}window.runCommandCb=function(){O(pui.p);pui.p=null};pui.runPCCommand=O;
pui.isServerBusy=function(){if(typeof context=="undefined")return false;if(context=="dspf"&&pui.n===false||context=="genie"&&pui.f.g===true)return true;for(var b=document.getElementsByTagName("iframe"),a=0;a<b.length;a++){var c=b[a].contentWindow;if(c!=null){var e=null;try{e=c.pui}catch(d){}if(e!=null)if(typeof e==="object")if(typeof e.isServerBusy==="function")if(e.isServerBusy())return true}}return false};
pui.showLastError=function(){if(errors.length==0)alert("No errors have been reported.");else{var b=errors.length-1;alert("Operation: "+errors[b].la+"\nId: "+errors[b].id+"\n\nMessage: "+errors[b].text+"\n"+errors[b].qa)}};
pui.editCode=function(b,a){function c(q,w){var x=["","","","nn/n","nn/nn","nn/nn/n","nn/nn/nn","nnn/nn/nn","nn/nn/nnnn","nnn/nn/nnnn"];if(i.dateEdit==="*ymd"){x[8]="nnnn/nn/nn";x[9]="nnnnn/nn/nn"}x=x[v];q=String(q);q=q.replace(".","");q=q.replace(",","");q=q.replace("-","");q="0000000000"+q;q=q.substr(q.length-w);var K="/";if(i.dateEditSeparator!=null)K=i.dateEditSeparator;for(var F=false,L=0,M="",E=0;E<x.length;E++){var A=x.substr(E,1),P=x.substr(E+1,1);if(A==="/"||P==="/")F=true;if(A==="/")A=K;
else{A=q.substr(L,1);L+=1;if(A==="0")F||(A=" ");else F=true}M+=A}return M}function e(q,w,x){for(q+="";q.length<w;)q+=x;return q}var d=null,h=0,f=null,i={},g=2;if(typeof arguments[g]==="number"){d=arguments[g];g++;if(typeof arguments[g]==="number"){h=arguments[g];g++}}if(typeof arguments[g]==="string"){f=arguments[g];g++}if(typeof arguments[g]==="object"){i=arguments[g];g++}var k=false;if(f==="*astfill"){k=true;f=null}var l=false,j=null,r=false,t=g=false;g=" ";if(pui.appJob&&typeof pui.appJob.decimalFormat===
"string")g=pui.appJob.decimalFormat;var n=g==="I"||g==="J",o=g==="J";if(i.decimalEdit!=null){n=i.decimalEdit===","||i.decimalEdit==="0,";o=i.decimalEdit==="0."||i.decimalEdit==="0,"}if(a>="1"&&a<="4")j="999.00";if(a>="A"&&a<="D")j="999.00CR";if(a>="J"&&a<="M")j="999.00-";if(a>="N"&&a<="Q")j="-999.00";if(a=="1"||a=="A"||a=="J"||a=="N"||a=="2"||a=="B"||a=="K"||a=="O")r=true;g=a=="1"||a=="A"||a=="J"||a=="N"||a=="3"||a=="C"||a=="L"||a=="P"?true:false;if(a=="Z")j="999.00";if(a==="X"||a==="Z")t=true;if(a===
"X")l=true;a>="5"&&a<="9"&&pui.alert("User-defined edit code not supported: "+a+".");a>="1"&&a<="9"||a>="A"&&a<="D"||a>="J"&&a<="Q"||a>="X"&&a<="Z"||pui.alert("Invalid edit code: "+a+".");var m=(b||0)+"",s=parseFloat(m,10)||0,p;p=m.replace(/\..*/,"");if(p==="-0")p="-";if((p==""||p=="-")&&o)p="0";var u;u=m;if(u.indexOf(".")==-1)u+=".";u=u.replace(/.*\./,"");var v=p.length;if(v<3)v=3;var B=u.length;if(typeof d==="number")v=d;if(typeof h==="number")B=h;if(a=="Y"){if(v<3||v>9)pui.alert("Length not valid for edit code Y.");
return c(s,v)}d=".";if(n)d=",";if(t)d="";if(B>0){u=e(u,B,"0");if(p==="0"&&!o)p="";m=p+d+u}var G=" ";if(l)G="0";if(k)G="*";if(r){for(h=/(\d+)(\d{3})/;h.test(p);)p=p.replace(h,"$1"+(n?".":",")+"$2");m=p+(B>0?d+u:"");n=v-B-1;n=n>=0?n:0}n=s<0;m=m.replace(/-/g,"");if(j==="(999.00)"){if(n)m="("+m+")"}else if(j==="999.00-")m+=n?"-":" ";else if(j==="999.00CR")m+=n?"CR":"  ";else if(j==="-999.00")if(n)m="-"+m;if(f)m=f=="EUR"?m+" EUR":f=="$"?m.substr(0,1)=="-"?"-"+f+m.substr(1):f+m:f+m;if(!g)if(s===0)m="";
(function(){var q=v;q+=B&&!t?1:0;if(r)q+=parseInt((v-B-1)/3);if(j==="999.00CR")q+=2;if(j==="999.00-")q+=1;if(j==="-999.00")q+=1;if(typeof f==="string")q+=f.length;var w=m;for(w+="";w.length<q;)w=G+w;m=w})();return m};
pui.editWord=function(b,a,c){function e(){if(o.length>0){var p=o.substr(o.length-1,1);o=o.substr(0,o.length-1);if(p=="0"&&o.length==0&&s)p=m?"*":" "}else{p="0";if(s)p=" ";if(m)p="*"}return p}b=String(b);var d={};if(typeof c==="object")d=c;c="$";if(d.currencySymbol!=null)c=d.currencySymbol;var h=a.indexOf("0")+1,f=a.indexOf("*")+1;if(h==0||f!=0&&f<h)h=f;for(var i=-1,g=a.length-1;g>=0;g-=1)if(g+1==h||a.substr(g,1)==" "){i=g;break}f=a.substr(0,i+1);var k="",l="",j=false,r=false,t=a.substr(i+1).indexOf("-")>=
0||a.substr(i+1).indexOf("CR")>=0;for(g=i+1;g<a.length;g++){var n=a.substr(g,1);if(a.substr(g,2)=="CR"){r=true;g++}else if(n=="-")r=true;else if(n!="&")if(!(n=="*"&&!r))if(n.toUpperCase()>="A"&&n.toUpperCase()<="Z"&&t&&!r)a=a.substr(0,g)+" "+a.substr(g+1);else{k=a.substring(i+1,g);l=a.substr(g);j=true;break}}j||(k=a.substr(i+1));g=".";n=" ";if(pui.appJob&&typeof pui.appJob.decimalFormat==="string")n=pui.appJob.decimalFormat;if(typeof d.decimalFormat==="string")n=d.decimalFormat;if(n==="I"||n==="J")g=
",";d=0;g=f.split(g);if(g.length>1)d=g[1].replace(/[^ ]/g,"").length;var o;o=isNaN(Number(b))?"0":String(b);o=o.replace("-","");g=o.split(".");n=g[0];a="";i=null;if(g.length>1)a=g[1];if(i==null||isNaN(i))i=d;for(;a.length>i;)a=a.substr(0,a.length-1);for(;i>a.length;)a+="0";for(o=n+a;o.substr(0,1)=="0";)o=o.substr(1);d="";var m=i=false;var s=a=false;if(h==0)s=true;for(g=f.length-1;g>=0;g-=1){j=n=f.substr(g,1);if(n==" ")j=e();else if(n=="&")j=" ";else if(n=="0"&&g+1==h)j=e();else if(n=="*"){m=true;
j=e()}else if(n==c){if(g+2==h){j=e();a=true}}else if(i){j=" ";if(m)j="*"}d=j+d;if(g<=h)s=true;if(s&&o.length==0)i=true}k=k.replace(/&/g," ");k=k.replace(/\*/g," ");if(b>=0){k=k.replace("CR","  ");k=k.replace("-"," ")}d=d+k+l;b=d.length-1;d=H(d);if(m&&d.substr(0,1)!="*")d="*"+d;if(a)d=c+d;c=0;if(d[d.length-1]==="-")c=1;for(;d.length<=b;)d=" "+d;return d};pui.m=navigator.userAgent.indexOf("Safari")!=-1&&navigator.userAgent.indexOf("Chrome")==-1;
pui.N=function(){for(var b=document.getElementById("auth-form"),a=document.cookie.split("; "),c=false,e=0;e<a.length;e++){var d=a[e].split("=");if(unescape(d[0])=="pui-signon-"+b.action)if(unescape(d[1])=="1"){c=true;break}}if(typeof Storage!="undefined"){a=N();if(a.workstnid)sessionStorage["atrium-params-workstnid"]=a.workstnid;else try{delete sessionStorage["atrium-params-workstnid"]}catch(h){}if(a.suffixid)sessionStorage["atrium-params-suffixid"]=a.suffixid;else try{delete sessionStorage["atrium-params-suffixid"]}catch(f){}if(a.duplicateid)sessionStorage["atrium-params-duplicateid"]=
a.duplicateid;else try{delete sessionStorage["atrium-params-duplicateid"]}catch(i){}}if(c)location.href=b.action;else{if(c=document.getElementById("auth-box"))c.style.display="";b.elements["auth-user"].focus()}};
pui.M=function(){var b=document.getElementById("auth-form"),a=b.elements["auth-user"].value,c=b.elements["auth-password"].value,e=document.getElementById("auth-message");e.innerHTML="";if(I(a)==""){e.innerHTML=authMessages["user required"];b.elements["auth-user"].focus();return false}else if(I(c)==""){e.innerHTML=authMessages["password required"];b.elements["auth-password"].focus();return false}pui.i(function(){var d=new pui.Ajax("/profoundui/pui0005010.pgm");d.async=true;d.method="POST";d.user=a;
d.password=c;if(pui.m){d.user=encodeURIComponent(d.user);d.password=encodeURIComponent(d.password)}d.suppressAlert=true;d.onready=function(h){if(h.c()==200){var f=eval("("+h.d()+")");h=f.days;var i=false;if(f.warn==true)if(h==0){f=authMessages["password expired"];pui.alert(f);i=true}else{f=authMessages["password pending expiration"];f=f.replace(/{DAYS}/g,h);i=confirm(f)}if(i){h="/profoundui/changepass";h+="?user="+encodeURIComponent(a);h+="&next="+encodeURIComponent(b.action);h+="&back="+encodeURIComponent(location.href);
location.href=h}else{document.cookie=escape("pui-signon-"+b.action)+"=1; path=/";location.href=b.action}}else{e.innerHTML=authMessages["invalid credentials"];b.elements["auth-user"].focus()}};d.send()});return false};pui.i=function(b){var a=new pui.Ajax("/profoundui/pui0005010.pgm");a.async=true;a.method="POST";a.user=a.password="PUI_SIGNOFF_USER";if(pui.m)a.user=a.password=encodeURIComponent(a.user);a.suppressAlert=true;a.onready=function(){typeof b=="function"&&b()};a.send()};
window.pui.signOn=pui.M;window.pui.clearCredentials=pui.i;window.pui.signOnInit=pui.N;pui.L=function(){var b=N(),a=document.getElementById("change-user"),c=document.getElementById("change-current"),e=a,d=document.getElementById("change-cancel");if(typeof b.user!="undefined"){a.value=b.user.toUpperCase();a.readOnly=true;a.className+=" read-only";e=c}if(typeof b.back=="undefined")d.style.display="none";document.getElementById("change-box").style.display="block";e.focus()};
pui.K=function(){var b=N();if(typeof b.back!="undefined")location.href=b.back};
pui.z=function(){var b=N(),a=document.getElementById("change-form"),c=a.elements["change-user"].value,e=a.elements["change-current"].value,d=a.elements["change-new"].value,h=a.elements["change-confirm"].value,f=document.getElementById("change-message");f.innerHTML="";if(I(c)==""){f.innerHTML=passMessages["user required"];a.elements["change-user"].focus();return false}else if(I(e)==""){f.innerHTML=passMessages["current required"];a.elements["change-current"].focus();return false}else if(I(d)==""){f.innerHTML=
passMessages["new required"];a.elements["change-new"].focus();return false}else if(I(h)==""){f.innerHTML=passMessages["confirm required"];a.elements["change-confirm"].focus();return false}else if(d!=h){f.innerHTML=passMessages["must match"];a.elements["change-new"].focus();return false}h=new pui.Ajax("/profoundui/pui0005011.pgm");h.async=true;h.method="POST";h.params={};h.params.user=c;h.params.current=e;h.params["new"]=d;h.suppressAlert=true;h.onready=function(i){if(i.c()!=200){f.innerHTML="HTTP "+
i.c()+" - "+i.k()+".";a.elements["change-user"].focus()}else{var g;try{g=eval("("+i.d()+")");if(typeof g.success!="boolean")throw"";if(!g.success&&typeof g.error!="string")throw"";}catch(k){g={};g.success=false;g.error="The server response is missing or invalid."}if(g.success==false){f.innerHTML=g.error;a.elements["change-user"].focus()}else{pui.alert(passMessages.success);pui.i(function(){var l=new pui.Ajax("/profoundui/pui0005010.pgm");l.async=true;l.method="POST";l.user=c;l.password=d;if(pui.m){l.user=
encodeURIComponent(l.user);l.password=encodeURIComponent(l.password)}l.suppressAlert=true;l.onready=function(j){if(j.c()==200){if(typeof b.next!="undefined")location.href=b.next}else{pui.alert("HTTP "+j.c()+" - "+j.k()+".");a.elements["change-user"].focus()}};l.send()})}}};h.send();return false};window.pui.passInit=pui.L;window.pui.passCancel=pui.K;window.pui.changePass=pui.z;
