window.pui||(window.pui={});window.pui.baseVersion="6";window.pui.fixPackVersion="1.0";window.pui.version=window.pui.baseVersion+"."+window.pui.fixPackVersion;window.init=r;window.checkUpdate=u;Ext.BLANK_IMAGE_URL="/ext-3.4.0/resources/images/default/s.gif";Ext.onReady(function(){});
var v=Array("RPG Development",1,"","","Start Visual Designer",2,"/profoundui/designer","","Launch Session",2,"/profoundui/start","","Launch Program Anonymously",2,"","anon","Online Documentation",2,"http://www.profoundlogic.com/docs","","Getting Started Videos",2,"http://www.youtube.com/ProfoundLogicTV","","Getting Started Guide",2,"http://www.profoundlogic.com/docs/display/PUI/Getting+Started","","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=53","","PHP Development",1,"",
"","Start Visual Designer",2,"/profoundui/viewdesigner","","Online Documentation",2,"http://www.profoundlogic.com/docs/display/PUI/PHP+Coding","","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=53","","Node.js Development",1,"","","Online Documentation",2,"http://www.profoundlogic.com/docs/display/PUI/Profound.js+Overview","","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=59","","Universal Display Files",1,"","","Start Editor",2,"/profoundui/universal",
"","Launch Program",2,"","uni","Online Documentation",2,"http://www.profoundlogic.com/docs/display/PUI/Universal+Display+Files","","JumpStart",1,"","","Start JumpStart",2,"/profoundui/jumpstart","","Online Documentation",2,"http://www.profoundlogic.com/docs/display/PUI/JumpStart",""),w=Array("Web-enable 5250 On-the-fly",1,"","","Start Genie Administrator",2,"/profoundui/genieadmin","","Launch Genie Skin",2,"","skins","Genie Development Guide",2,"http://www.profoundlogic.com/docs/display/PUI/Genie",
"","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=38","","Convert Green Screens",1,"","","Convert DDS Source",2,"/profoundui/designer?convert=true","","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=53",""),x=Array("Create a Web Portal",1,"","","Start Atrium",2,"/profoundui/atrium","","Atrium User Guide",2,"http://www.profoundlogic.com/docs/display/PUI/Atrium","","Forum",2,"http://www.profoundlogic.com/forums/phpbb3/viewforum.php?f=52","");
function r(){document.getElementById("version").innerHTML=pui.baseVersion+", Fix Pack "+pui.fixPackVersion;y("devMenu",v,"Orange");y("modMenu",w,"Green");y("intMenu",x,"Blue");z("skins","Green");A("anon","Orange");B();C(document.getElementById("Green1"),"Green");C(document.getElementById("Green2"),"Green");C(document.getElementById("Blue1"),"Blue");u(true)}
function y(f,d,a){for(var e="/profoundui/proddata/images/splash/"+a+".gif",g=document.getElementById(f),c,b,i,h,j=0,q=0,m=0,k=0;k<d.length/4;k++){b=d[k*4];c=d[k*4+1];i=d[k*4+2];h=d[k*4+3];var o=document.createElement("img");o.id=f+"b"+k;o.src=e;var p=document.createElement("a");p.innerHTML=b;if(i!=""){p.href=i;p.target="_blank"}b=document.createElement("div");b.className="menuLine level"+c;b.name="level"+c;if(h!="")b.id=h;if(c==1){c=document.createElement("img");c.src="/profoundui/proddata/images/splash/"+
a+"-Plus.png";c.className="expander";b.appendChild(c);b.onclick=function(){C(this,a)};if(a=="Orange"){j++;b.id=a+j}if(a=="Green"){q++;b.id=a+q}if(a=="Blue"){m++;b.id=a+m}}else if(c==2&&h!=""){c=document.createElement("img");c.src="/profoundui/proddata/images/splash/"+a+"-Plus.png";c.className="expander";b.appendChild(c);b.onclick=function(){var l=this,n=l.firstChild,s=l.name,t;if(n.src.indexOf("Plus.png")>=0){t="block";n.src="/profoundui/proddata/images/splash/"+a+"-Minus.png"}else{t="none";n.src=
"/profoundui/proddata/images/splash/"+a+"-Plus.png"}for(;l.nextSibling&&l.nextSibling.name!=s;){l=l.nextSibling;l.style.display=t}};b.style.display="none"}else{b.style.display="none";b.appendChild(o)}b.appendChild(p);g.appendChild(b)}}
function C(f,d){var a=f.firstChild,e=f.name,g,c;if(a.src.indexOf("Plus.png")>=0){g="block";a.src="/profoundui/proddata/images/splash/"+d+"-Minus.png"}else{g="none";a.src="/profoundui/proddata/images/splash/"+d+"-Plus.png"}if(g=="none")for(;f.nextSibling&&f.nextSibling.name!=e;){f=f.nextSibling;f.style.display=g}else for(;f.nextSibling&&f.nextSibling.name!=e;){f=f.nextSibling;f.style.display=f.name=="level3"?c:g;if(f.name=="level2"&&f.id!="")c=f.firstChild.src.indexOf("Plus")>=0?"none":"block";else if(f.name!=
"level3")c="block"}}function z(f,d){var a=new pui.Ajax("/profoundui/PUI0004001.pgm");a.async=true;a.method="POST";a.onfail=function(){alert("Error Loading Skins")};a.onsuccess=function(){for(var e=eval("("+a.a()+")"),g=document.getElementById(f),c,b,i="/profoundui/proddata/images/splash/"+d+".gif",h=0;h<e.length;h++){c=e[h];b="/profoundui/genie?skin="+e[h];D(g,c,b,i)}};a.send()}
function A(f,d){var a=new pui.Ajax("/profoundui/PUI0001105.pgm");a.async=true;a.method="POST";a.postData="Mode=load";a.onfail=function(){alert("Error Loading Anonymous Programs")};a.onsuccess=function(){for(var e=eval("("+a.a()+")").programs,g=document.getElementById(f),c,b,i="/profoundui/proddata/images/splash/"+d+".gif",h=0;h<e.length;h++){c=e[h].split("/");c=c.length==2?c[0].toLowerCase()+" / "+c[1]:e[h];b="/profoundui/start?pgm="+e[h];D(g,c,b,i)}};a.send()}
function B(){var f=new pui.Ajax("/profoundui/PUI0001105.pgm");f.async=true;f.method="POST";f.postData="Mode=load&set=uni";f.onfail=function(){alert("Error Loading Universal Display File Programs")};f.onsuccess=function(){for(var d=eval("("+f.a()+")").programs,a=document.getElementById("uni"),e,g,c=0;c<d.length;c++){var b=d[c].uri;e=b;g=HTTPS=="ON"?"https://":"http://";g+=HTTP_HOST;g+=d[c].auth?PUI_UNIVERSAL_AUTH:PUI_UNIVERSAL;g+=b;D(a,e,g,"/profoundui/proddata/images/splash/Orange.gif")}};f.send()}
function D(f,d,a,e){var g=document.createElement("img");g.src=e;e=document.createElement("a");e.href=a;e.target="_blank";e.innerHTML=d;d=document.createElement("div");d.className="menuLine level3";d.name="level3";d.style.display="none";d.appendChild(g);d.appendChild(e);f.nextSibling?f.parentNode.insertBefore(d,f.nextSibling):f.parentNode.appendChild(d)}
function u(f){var d;if(!f){d=new Ext.LoadMask(Ext.getBody());d.msg="Checking for udpate...";d.show()}(new Ext.data.ScriptTagProxy({url:UPDATE_SITE+"prdversion.rpgsp",timeout:1E4})).doRequest("read",null,{product:"profoundui",version:window.pui.version,system:SYSTEM,serial:SERIAL,pgroup:PGROUP,os:OSRELEASE},new Ext.data.JsonReader({root:"response"},Ext.data.Record.create([{name:"version"}])),function(a,e,g){f||d.hide();if(g==true){a=a.records[0].get("version");if(window.pui.version!=a||!f)E(pui.version,
a)}else f||Ext.MessageBox.show({title:"Error",icon:Ext.MessageBox.ERROR,buttons:Ext.MessageBox.OK,msg:'Unable to connect to the Profound UI update server. Either your PC is not connected to the Internet or the update server is temporarily unavailable.<br /><br />For information on Profound UI, including product updates, please contact Profound Logic.<br /><br />Toll free: 1-877-224-7768<br />Email: <a href="mailto:sales@profoundlogic.com&subject=Profound UI">sales@profoundlogic.com</a><br />Web: <a href="http://www.profoundlogic.com" target="_blank">www.profoundlogic.com</a>'})})}
function E(f,d){var a,e=d.split(".");a=e.shift();e=e.join(".");if(e==="0.0")e="0";if(f==d)a="You have the most current version of Profound UI (Version "+a+", Fix Pack "+e+").";else{a="A new release of Profound UI (Version "+a+", Fix Pack "+e+") is available.";a+='<br /><br /><a href="http://www.profoundlogic.com/download?product=profoundui" target="_blank">Click here</a> to download the new release.'}a+='<br /><br /><a href="'+UPDATE_SITE+'versions.rpgsp?product=profoundui" target="_blank">Click here</a> to see the version history.';
var g=new Ext.Window({title:"Profound UI",width:425,modal:true,resizable:false,closable:true,items:[new Ext.Panel({bodyStyle:"padding: 5px;",html:a})],buttons:[{text:"OK",handler:function(){g.close()}}]});g.show()};function F(f){this.onready=this.onfail=this.onsuccess=this.suppressAlert=this.password=this.user=this.async=this.url=this.postData=this.method=null;this.headers={};this.params=null;this.sendAsBinary=true;var d=null,a=null,e=null,g=null,c=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert,b=this;if(typeof f=="object")for(var i in f){if(typeof this[i]!="undefined")this[i]=f[i]}else this.url=f;if(window.XMLHttpRequest)d=new XMLHttpRequest;else if(window.ActiveXObject)d=new ActiveXObject("Microsoft.XMLHTTP");
else{c("Ajax request error: Unsupported browser.");return}this.send=this.send=function(){function h(){if(d.readyState==4){a=d.status+" - "+d.statusText;b.onready!=null&&b.onready(b);if(d.status==200){e=true;b.onsuccess!=null&&b.onsuccess(b)}else{e=false;b.suppressAlert!=true&&c(a);b.onfail!=null&&b.onfail(b)}g=false}}var j=null,q=null,m=null;if(b.method==null)j="GET";else if(typeof b.method!="string"&&(b.method.toUpperCase()!="GET"||b.method.toUpperCase()!="POST"||b.method.toUpperCase()!="PUT")){c('Invalid value for property: "method".');
return}else j=b.method.toUpperCase();if(j=="POST")if(b.postData!=null)if(typeof b.postData!="string"){c('Invalid value for property: "postData".');return}else m=b.postData;else m="";if(b.async==null)q=true;else if(b.async!=true&&b.async!=false){c('Invalid value for property: "async".');return}else q=b.async;if(typeof b.url!="string")c('Invalid value for property: "url".');else{if(b.user!=null)if(typeof b.user!="string"){c('Invalid value for property: "user".');return}if(b.password!=null)if(typeof b.password!=
"string"){c('Invalid value for property: "password".');return}if(b.onsuccess!=null)if(typeof b.onsuccess!="function"){c('Invalid value for event: "onsuccess".');return}if(b.onfail!=null)if(typeof b.onfail!="function"){c('Invalid value for event: "onfail".');return}if(b.onready!=null)if(typeof b.onready!="function"){c('Invalid value for event: "onready".');return}var k=b.url,o=b.params;if(typeof o=="object"){var p="";for(var l in o){var n=o[l],s=[];if(typeof n=="object"){if(n.length!=null&&n.length>
0)s=n}else s.push(n);for(n=0;n<s.length;n++){if(p!="")p+="&";p+=encodeURIComponent(l)+"="+encodeURIComponent(s[n])}}if(p!="")if(j.toUpperCase()=="POST"){if(m!=null&&m!="")m+="&";else m="";m+=p}else{o=k.split("?");if(o.length==2&&o[1]!="")k=o[0]+"?"+o[1]+"&"+p;else k+="?"+p}}try{typeof b.user=="string"&&typeof b.password=="string"?d.open(j,k,q,b.user,b.password):d.open(j,k,q);k=false;var t=b.headers;for(l in t){d.setRequestHeader(l,t[l]);if(l.toUpperCase()=="CONTENT-TYPE")k=true}if(j=="POST")k||d.setRequestHeader("Content-type",
"application/x-www-form-urlencoded")}catch(G){c(G);return}g=true;if(q==true)d.onreadystatechange=h;if(b.sendAsBinary==true)try{d.sendAsBinary(m)}catch(H){d.send(m)}else d.send(m);q!=true&&h()}};this.ok=this.f=function(){return e!=null?e:false};this.getResponseText=this.a=function(){return d.responseText};this.getResponseXML=this.b=function(){return d.responseXML};this.getStatus=this.c=function(){return d.status};this.getStatusText=this.e=function(){return d.statusText};this.getStatusMessage=this.d=
function(){return a};this.getAllResponseHeaders=this.getAllResponseHeaders=function(){if(e)try{return d.getAllResponseHeaders()}catch(h){c(h)}};this.getResponseHeader=this.getResponseHeader=function(h){if(e)try{return d.getResponseHeader(h)}catch(j){c(j)}};this.setRequestHeader=this.setRequestHeader=function(h,j){b.headers[h]=j};this.abort=this.abort=function(){if(!(g==null||g==true))try{d.abort()}catch(h){c(h)}}}if(typeof window.pui=="undefined")window.pui={};window.RPGspRequest=F;
window.pui.Ajax=F;window.pui.AjaxRequest=F;window.ajax=function(f,d){var a,e,g,c="";if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;if(typeof a.handler=="function"){e=true;g=a.handler}else e=false}else if(d!=null&&typeof d=="function"){e=true;g=d}else e=false;a=new F(arguments[0]);a.async=e;a.onsuccess=function(b){c+=b.a();e==true&&g(c)};a.send();if(e==false)return c};
window.ajaxXML=function(f,d){var a,e,g,c=null;if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;a.onfail=null;a.onsuccess=null;if(typeof a.handler=="function"){e=true;g=a.handler}else e=false}else if(d!=null&&typeof d=="function"){e=true;g=d}else e=false;a=new F(arguments[0]);a.async=e;a.onsuccess=function(b){c=b.b();e==true&&g(c)};a.send();if(e==false)return c};
window.ajaxJSON=function(f,d){var a,e,g,c=null,b=false;if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;if(a.saveResponse==true)b=true;if(typeof a.handler=="function"){e=true;g=a.handler}else e=false}else if(d!=null&&typeof d=="function"){e=true;g=d}else e=false;a=new F(arguments[0]);a.async=e;a.onsuccess=function(i){i=i.a();if(b&&typeof pui=="object")pui.savedJSON=i;try{c=eval("("+i+")")}catch(h){g(null,h);return}e==true&&g(c)};a.send();if(e==false)return c};
window.ajaxSubmit=function(f,d){var a,e="",g=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert;if(typeof f=="object")a=f;else{a=document.getElementById(f);if(a==null)a=document.forms[f]}var c;if(a!=null)c=a.tagName;if(a==null||c==null||c.toUpperCase()!="FORM"){g("Ajax request error: Invalid form object.");return""}if(f.action==""){g("Ajax request error: Invalid form action.");return""}for(g=0;g<a.elements.length;g++){c=a.elements[g];if(c.name!=null&&c.name!=""){var b=false;if(c.tagName==
"INPUT"){var i=c.type;i=i.toLowerCase();if(i=="hidden")b=true;if(i=="password")b=true;if(i=="text")b=true;if(pui.g(i))b=true;if(i=="")b=true;if(i=="checkbox"||i=="radio")if(c.checked)b=true}if(c.tagName=="TEXTAREA")b=true;if(c.tagName=="SELECT")b=true;if(b){if(e!="")e+="&";e+=c.name+"="+encodeURIComponent(c.value)}}}a=new F(a.action);a.method="POST";a.postData=e;var h="",j;if(d!=null&&typeof d=="function")j=true;else{j=false;a.async=false}a.onsuccess=function(q){h+=q.a();j==true&&d(h)};a.send();if(j==
false)return h};
